services:
  btcrpcexplorer:
    build:
      context: .
      args:
        BTCEXP_VERSION: ${BTCEXP_VERSION}
        BTCEXP_GID: ${BTCEXP_GID}
        BTCEXP_UID: ${BTCEXP_UID}
    container_name: ${COMPOSE_PROJECT_NAME}_btcrpcexplorer
    depends_on:
      - bitcoin
    expose:
      - "3002"
    healthcheck:
      test: ["CMD-SHELL", "curl -fk http://localhost:3002 >/dev/null || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
    image: ${COMPOSE_PROJECT_NAME}/btcrpcexplorer:${BTCEXP_VERSION}
    restart: unless-stopped
    volumes:
      - ./btcrpcexplorer.env:/home/node/.env
      - bitcoin-data:/data/bitcoin/:ro

volumes:
  btcrpcexplorer-conf: