services:
  bitcoin:
    build:
      context: .
      args:
        BITCOIN_VERSION: ${BITCOIN_VERSION}
        BITCOIN_GID: ${BITCOIN_GID}
        BITCOIN_UID: ${BITCOIN_UID}
        TOR_GID: ${TOR_GID}
    container_name: ${COMPOSE_PROJECT_NAME}_bitcoin
    expose:
      - "8332"
      - "8334"
    healthcheck:
      test: ["CMD-SHELL", "bitcoin-cli getconnectioncount | sed 's/^[1-9][0-9]*$/OK/' | grep OK || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5m
    image: ${COMPOSE_PROJECT_NAME}/bitcoin:${BITCOIN_VERSION}
    networks:
      default:
        ipv4_address: ${BITCOIN_ADDRESS}
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin/
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf:ro
      - tor-data:/var/lib/tor/

volumes:
  bitcoin-data:
